version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Password
      - MSSQL_DB=yourdatabase
    ports:
      - "1433:1433"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  sqlvolume:
    driver: local
